//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonicRetro.SonicAdventure.SADXPCDecompiler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonicRetro.SonicAdventure.SADXPCDecompiler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address &quot;{0:X8}&quot; does not refer to an ATTACH structure..
        /// </summary>
        internal static string AddressDoesNotReferToAttach {
            get {
                return ResourceManager.GetString("AddressDoesNotReferToAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output directory could not be found..
        /// </summary>
        internal static string DirectoryNotFoundForOutputDirectory {
            get {
                return ResourceManager.GetString("DirectoryNotFoundForOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory that should contain an output file was not found..
        /// </summary>
        internal static string DirectoryOfOutputFileNotFound {
            get {
                return ResourceManager.GetString("DirectoryOfOutputFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &lt;Rename&gt; element has an invalid Address attribute: &quot;{0}&quot;. The Address attribute must be a string of one to eight hexadecimal characters..
        /// </summary>
        internal static string InvalidAddress {
            get {
                return ResourceManager.GetString("InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path for the module description file is invalid..
        /// </summary>
        internal static string InvalidPathForModuleDescription {
            get {
                return ResourceManager.GetString("InvalidPathForModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path for the output directory or a subdirectory thereof is invalid..
        /// </summary>
        internal static string InvalidPathForOutputDirectory {
            get {
                return ResourceManager.GetString("InvalidPathForOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path for an output file is invalid..
        /// </summary>
        internal static string InvalidPathForOutputFile {
            get {
                return ResourceManager.GetString("InvalidPathForOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path for the source module file is invalid..
        /// </summary>
        internal static string InvalidPathForSourceModule {
            get {
                return ResourceManager.GetString("InvalidPathForSourceModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An I/O error occurred while trying to create an output file..
        /// </summary>
        internal static string IOErrorForOutputFile {
            get {
                return ResourceManager.GetString("IOErrorForOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An I/O error occurred while trying to write in an output file..
        /// </summary>
        internal static string IOErrorWhileWritingInOutputFile {
            get {
                return ResourceManager.GetString("IOErrorWhileWritingInOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source module doesn&apos;t export &quot;{0}&quot;..
        /// </summary>
        internal static string MissingExport {
            get {
                return ResourceManager.GetString("MissingExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module description file was not found..
        /// </summary>
        internal static string ModuleDescriptionFileNotFound {
            get {
                return ResourceManager.GetString("ModuleDescriptionFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path for the module description file is too long..
        /// </summary>
        internal static string PathTooLongForModuleDescription {
            get {
                return ResourceManager.GetString("PathTooLongForModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path for the output directory or a subdirectory thereof is too long..
        /// </summary>
        internal static string PathTooLongForOutputDirectory {
            get {
                return ResourceManager.GetString("PathTooLongForOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path for an output file is too long..
        /// </summary>
        internal static string PathTooLongForOutputFile {
            get {
                return ResourceManager.GetString("PathTooLongForOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path for the source module file is too long..
        /// </summary>
        internal static string PathTooLongForSourceModule {
            get {
                return ResourceManager.GetString("PathTooLongForSourceModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source module file was not found..
        /// </summary>
        internal static string SourceModuleFileNotFound {
            get {
                return ResourceManager.GetString("SourceModuleFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the module description file was denied, or the specified path is a directory..
        /// </summary>
        internal static string UnauthorizedAccessToModuleDescription {
            get {
                return ResourceManager.GetString("UnauthorizedAccessToModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the output directory or a subdirectory thereof was denied..
        /// </summary>
        internal static string UnauthorizedAccessToOutputDirectory {
            get {
                return ResourceManager.GetString("UnauthorizedAccessToOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to an output file was denied, or the specified path is a directory..
        /// </summary>
        internal static string UnauthorizedAccessToOutputFile {
            get {
                return ResourceManager.GetString("UnauthorizedAccessToOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the source module file was denied, or the specified path is a directory..
        /// </summary>
        internal static string UnauthorizedAccessToSourceModule {
            get {
                return ResourceManager.GetString("UnauthorizedAccessToSourceModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An &lt;Export&gt; element has an unknown child element..
        /// </summary>
        internal static string UnknownExportChild {
            get {
                return ResourceManager.GetString("UnknownExportChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;Rename&gt; element referring to address &quot;{0:X8}&quot; doesn&apos;t point to a known object..
        /// </summary>
        internal static string UnknownObject {
            get {
                return ResourceManager.GetString("UnknownObject", resourceCulture);
            }
        }
    }
}
