//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonicRetro.SonicAdventure.PCTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonicRetro.SonicAdventure.PCTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of offset and count is larger than the buffer length..
        /// </summary>
        internal static string OffsetPlusCountGreaterThanBufferLength {
            get {
                return ResourceManager.GetString("OffsetPlusCountGreaterThanBufferLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations on a disposed PEReader instance are not allowed..
        /// </summary>
        internal static string PEReaderDisposed {
            get {
                return ResourceManager.GetString("PEReaderDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations on a disposed VirtualMemoryStream instance are not allowed..
        /// </summary>
        internal static string VirtualMemoryStreamDisposed {
            get {
                return ResourceManager.GetString("VirtualMemoryStreamDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 0x{0} is located outside of a section in the image..
        /// </summary>
        internal static string VirtualMemoryStreamOutOfASection {
            get {
                return ResourceManager.GetString("VirtualMemoryStreamOutOfASection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the length of a VirtualMemoryStream is not supported..
        /// </summary>
        internal static string VirtualMemoryStreamSetLengthNotSupported {
            get {
                return ResourceManager.GetString("VirtualMemoryStreamSetLengthNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing to a VirtualMemoryStream is not supported..
        /// </summary>
        internal static string VirtualMemoryStreamWriteNotSupported {
            get {
                return ResourceManager.GetString("VirtualMemoryStreamWriteNotSupported", resourceCulture);
            }
        }
    }
}
