//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonicRetro.SonicAdventure.CExporter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonicRetro.SonicAdventure.CExporter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The animation frame collection contains a null animation frame..
        /// </summary>
        internal static string AnimFrameCollectionContainsNull {
            get {
                return ResourceManager.GetString("AnimFrameCollectionContainsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the animation frames in the collection is not the same for all animation frames..
        /// </summary>
        internal static string AnimFrameCollectionIsNotHomogeneous {
            get {
                return ResourceManager.GetString("AnimFrameCollectionIsNotHomogeneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection is empty..
        /// </summary>
        internal static string EmptyCollection {
            get {
                return ResourceManager.GetString("EmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &quot;{0}&quot; is not a valid C identifier..
        /// </summary>
        internal static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The polygon collection contains a null polygon..
        /// </summary>
        internal static string PolyCollectionContainsNull {
            get {
                return ResourceManager.GetString("PolyCollectionContainsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the polygons in the collection is not the same for all polygons..
        /// </summary>
        internal static string PolyCollectionIsNotHomogeneous {
            get {
                return ResourceManager.GetString("PolyCollectionIsNotHomogeneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of polygons in one of the meshes in the collection is too large..
        /// </summary>
        internal static string PolyCountInMeshTooHigh {
            get {
                return ResourceManager.GetString("PolyCountInMeshTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the animation frame is unknown..
        /// </summary>
        internal static string UnknownTypeOfAnimFrame {
            get {
                return ResourceManager.GetString("UnknownTypeOfAnimFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of vertices in a strip is too large..
        /// </summary>
        internal static string VertexCountInStripTooHigh {
            get {
                return ResourceManager.GetString("VertexCountInStripTooHigh", resourceCulture);
            }
        }
    }
}
